Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\maria_havens_pos\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\maria_havens_pos\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\maria_havens_pos\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden: /api/menu/categories/
"GET /api/menu/categories/ HTTP/1.1" 403 58
- Broken pipe from ('127.0.0.1', 55440)
C:\Users\DELL\Desktop\New Maria Havens\backend\menu\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /api/menu/categories/ HTTP/1.1" 200 1206
- Broken pipe from ('127.0.0.1', 55470)
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden: /api/orders/tables/
"GET /api/orders/tables/ HTTP/1.1" 403 58
- Broken pipe from ('127.0.0.1', 49562)
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\urls.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /api/menu/categories/ HTTP/1.1" 200 1206
- Broken pipe from ('127.0.0.1', 51458)
"GET /api/orders/ HTTP/1.1" 200 293
- Broken pipe from ('127.0.0.1', 51482)
"GET /api/orders/orders/ HTTP/1.1" 200 1004
- Broken pipe from ('127.0.0.1', 51509)
"GET /api/orders/tables/ HTTP/1.1" 200 1309
- Broken pipe from ('127.0.0.1', 51532)
"GET /api/menu/categories/ HTTP/1.1" 200 1206
Forbidden: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 403 58
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"GET /api/orders/orders/ HTTP/1.1" 200 1004
"GET /api/orders/tables/ HTTP/1.1" 200 1309
Internal Server Error: /api/orders/orders/
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py", line 69, in perform_create
    order = serializer.save(server=getattr(self.request, 'user', None))
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py", line 90, in create
    order = Order.objects.create(**validated_data)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
    ...<7 lines>...
    )
ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x0000020F74A1C870>": "Order.server" must be a "User" instance.
"POST /api/orders/orders/ HTTP/1.1" 500 148415
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /api/menu/categories/ HTTP/1.1" 200 1206
Forbidden: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 403 58
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"GET /api/orders/orders/ HTTP/1.1" 200 1004
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"POST /api/orders/orders/ HTTP/1.1" 201 520
Forbidden: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 403 58
C:\Users\DELL\Desktop\New Maria Havens\backend\menu\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\menu\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\menu\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\menu\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\menu\views.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\menu\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\Desktop\New Maria Havens\backend\menu\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /api/menu/categories/ HTTP/1.1" 200 1206
"GET /api/menu/items/ HTTP/1.1" 200 2919
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"GET /api/orders/orders/ HTTP/1.1" 200 1234
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"POST /api/orders/orders/ HTTP/1.1" 201 521
"GET /api/menu/items/ HTTP/1.1" 200 2919
Bad Request: /api/orders/order-items/
"POST /api/orders/order-items/ HTTP/1.1" 400 85
"GET /api/menu/categories/ HTTP/1.1" 200 1206
"GET /api/menu/items/ HTTP/1.1" 200 2919
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"GET /api/orders/orders/ HTTP/1.1" 200 1465
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"POST /api/orders/orders/ HTTP/1.1" 201 521
"GET /api/menu/items/ HTTP/1.1" 200 2919
Bad Request: /api/orders/order-items/
"POST /api/orders/order-items/ HTTP/1.1" 400 85
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py changed, reloading.
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /api/menu/categories/ HTTP/1.1" 200 1206
"GET /api/menu/items/ HTTP/1.1" 200 2919
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"GET /api/orders/orders/ HTTP/1.1" 200 1696
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"POST /api/orders/orders/ HTTP/1.1" 201 521
"GET /api/menu/items/ HTTP/1.1" 200 2919
Internal Server Error: /api/orders/order-items/
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: orders_orderitem.order_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py", line 263, in perform_create
    order_item = serializer.save()
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py", line 57, in create
    order_item = OrderItem.objects.create(**validated_data)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\models.py", line 129, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: orders_orderitem.order_id
"POST /api/orders/order-items/ HTTP/1.1" 500 227849
Watching for file changes with StatReloader
"GET /api/menu/items/ HTTP/1.1" 200 2919
"GET /api/orders/orders/ HTTP/1.1" 200 1927
Internal Server Error: /api/orders/order-items/
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: orders_orderitem.order_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py", line 263, in perform_create
    order_item = serializer.save()
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py", line 57, in create
    order_item = OrderItem.objects.create(**validated_data)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\models.py", line 129, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: orders_orderitem.order_id
"POST /api/orders/order-items/ HTTP/1.1" 500 227556
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py changed, reloading.
Watching for file changes with StatReloader
"GET /api/menu/items/ HTTP/1.1" 200 2919
"GET /api/orders/orders/ HTTP/1.1" 200 1927
Bad Request: /api/orders/order-items/
"POST /api/orders/order-items/ HTTP/1.1" 400 37
C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py changed, reloading.
Watching for file changes with StatReloader
"GET /api/menu/items/ HTTP/1.1" 200 2919
"GET /api/orders/orders/ HTTP/1.1" 200 1927
"POST /api/orders/order-items/ HTTP/1.1" 201 891
"GET /api/menu/categories/ HTTP/1.1" 200 1206
"GET /api/menu/items/ HTTP/1.1" 200 2919
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"GET /api/orders/orders/ HTTP/1.1" 200 1928
"GET /api/orders/tables/ HTTP/1.1" 200 1309
"POST /api/orders/orders/ HTTP/1.1" 201 521
"GET /api/menu/items/ HTTP/1.1" 200 2919
"POST /api/orders/order-items/ HTTP/1.1" 201 892
"POST /api/orders/orders/13/confirm/ HTTP/1.1" 200 28
Internal Server Error: /api/orders/order-items/
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\views.py", line 263, in perform_create
    order_item = serializer.save()
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\serializers.py", line 57, in create
    order_item = OrderItem.objects.create(**validated_data)
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\New Maria Havens\backend\orders\models.py", line 128, in save
    self.subtotal = self.quantity * self.unit_price
                    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4159
"OPTIONS /api/accounts/login/ HTTP/1.1" 200 0
Bad Request: /api/accounts/login/
"POST /api/accounts/login/ HTTP/1.1" 400 51
Bad Request: /api/accounts/login/
"POST /api/accounts/login/ HTTP/1.1" 400 51
Bad Request: /api/accounts/login/
"POST /api/accounts/login/ HTTP/1.1" 400 51
Bad Request: /api/accounts/login/
"POST /api/accounts/login/ HTTP/1.1" 400 51
Watching for file changes with StatReloader
"GET /api/ HTTP/1.1" 200 2
- Broken pipe from ('127.0.0.1', 58085)
Bad Request: /api/accounts/login/
"POST /api/accounts/login/ HTTP/1.1" 400 51
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2987
- Broken pipe from ('127.0.0.1', 59034)
"GET /api/ HTTP/1.1" 200 2
- Broken pipe from ('127.0.0.1', 59055)
Bad Request: /api/accounts/login/
"POST /api/accounts/login/ HTTP/1.1" 400 37
- Broken pipe from ('127.0.0.1', 59105)
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4159
Bad Request: /api/accounts/login/
"POST /api/accounts/login/ HTTP/1.1" 400 51
Bad Request: /api/accounts/login/
"POST /api/accounts/login/ HTTP/1.1" 400 51
- Broken pipe from ('127.0.0.1', 59550)
"POST /api/accounts/login/ HTTP/1.1" 200 457
- Broken pipe from ('127.0.0.1', 59657)
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4159
"POST /api/accounts/login/ HTTP/1.1" 200 457
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 302 0
Not Found: /api/auth/login/
"POST /api/auth/login/ HTTP/1.1" 404 3318
Not Found: /api/auth/login/
"POST /api/auth/login/ HTTP/1.1" 404 3318
- Broken pipe from ('127.0.0.1', 60368)
"POST /api/accounts/login/ HTTP/1.1" 200 457
- Broken pipe from ('127.0.0.1', 60479)
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 302 0
"POST /api/accounts/login/ HTTP/1.1" 200 457
"POST /api/accounts/login/ HTTP/1.1" 200 473
"POST /api/accounts/login/ HTTP/1.1" 200 487
"POST /api/accounts/login/ HTTP/1.1" 200 469
"POST /api/accounts/login/ HTTP/1.1" 200 474
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 302 0
"POST /api/accounts/login/ HTTP/1.1" 200 457
- Broken pipe from ('127.0.0.1', 65117)
"POST /api/accounts/login/ HTTP/1.1" 200 487
- Broken pipe from ('127.0.0.1', 65132)
Forbidden: /api/accounts/users/
"GET /api/accounts/users/ HTTP/1.1" 403 58
- Broken pipe from ('127.0.0.1', 49379)
"GET /api/menu/items/ HTTP/1.1" 200 2919
- Broken pipe from ('127.0.0.1', 49605)
Watching for file changes with StatReloader
Not Found: /
- Broken pipe from ('127.0.0.1', 49275)
Not Found: /
"GET / HTTP/1.1" 404 2987
- Broken pipe from ('127.0.0.1', 49464)
Watching for file changes with StatReloader
